name: ci
on:
  push:
    branches:
      - main
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-with-pdf weasyprint==54.3
      - run: mkdocs gh-deploy --force -f config/en/mkdocs.yml
      - run: mkdocs gh-deploy --force -f config/nl/mkdocs.yml
